source 'https://rubygems.org'
gem 'rack'
gem 'rack-test'
gem 'redis'
gem 'ohm', '2.1.0'
gem 'ohm-zset'
gem 'ohm-contrib'
gem 'ohm-stateful-model'
gem 'grape'
gem 'faraday'
gem 'faraday-detailed_logger'
gem 'logger'
gem 'xml-simple'
gem 'roo'
gem 'digest'
gem 'minitest'